### ISSUE TITLE
relative links not working

### ISSUE THREAD

**Issue by PandaWhoCodes** [prodicus/tasdikrahman.me#1]
relative links for older posts does not function. 
A / needs to be added before pageNumber

**Comment by tasdikrahman** [comment]
Hello there, sorry for the late reply, missed the notifications. 

Have fixed it here in this commit https://github.com/tasdikrahman/tasdikrahman.me/commit/ca34aa2aef97831abe02d94a68199197cb975963

Thanks for dropping by :)
